packages:
  - apps/*
  - packages/*
includeWorkspaceRoot: true

onlyBuiltDependencies:
  - sharp
  - esbuild

overrides:
  '@the-civia-project/prettier-config': link:./packages/prettier-config
  '@the-civia-project/amqp': link:./packages/amqp
  '@the-civia-project/logger': link:./packages/logger
  '@the-civia-project/db': link:./packages/db
  '@the-civia-project/core': link:./packages/core
  '@the-civia-project/emails': link:./packages/emails
  'esbuild': 'npm:esbuild@0.25.10'
